[versions]
tbdLibs = "2026.01.22-09.16-1d3f6039"
sykepengerGradlePlugins = "20261001.1830"

[libraries]
awaitility = "org.awaitility:awaitility:4.2.0"
flyway-database-postgresql = "org.flywaydb:flyway-database-postgresql:11.5.0"
hikaricp = "com.zaxxer:HikariCP:6.3.0"
jsonassert = "org.skyscreamer:jsonassert:1.5.3"
kotliquery = "com.github.seratch:kotliquery:1.9.0"
ktor-client-cio = { module = "io.ktor:ktor-client-cio" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
mockk = "io.mockk:mockk:1.13.17"
postgresql = "org.postgresql:postgresql:42.7.7"
rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026011411051768385145.e8ebad1177b4"
tbdLibs-naisfulApp = { module = "com.github.navikt.tbd-libs:naisful-app", version.ref = "tbdLibs" }
tbdLibs-naisfulTestApp = { module = "com.github.navikt.tbd-libs:naisful-test-app", version.ref = "tbdLibs" }
tbdLibs-postgresTestdatabaser = { module = "com.github.navikt.tbd-libs:postgres-testdatabaser", version.ref = "tbdLibs" }
tbdLibs-signedJwtIssuerTest = { module = "com.github.navikt.tbd-libs:signed-jwt-issuer-test", version.ref = "tbdLibs" }

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
