apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spokelse
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  ingresses:
  - https://spokelse.intern.dev.nav.no
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 1
    max: 2
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: fpsak
          namespace: teamforeldrepenger
          cluster: dev-fss
        - application: fprisk
          namespace: teamforeldrepenger
          cluster: dev-fss
        - application: fpabakus
          namespace: teamforeldrepenger
          cluster: dev-fss
        - application: k9-abakus
          namespace: k9saksbehandling
          cluster: dev-fss
        - application: spapi
    outbound:
      external:
        - host: sykepengeperioder-api.dev-fss-pub.nais.io
  gcp:
    sqlInstances:
    - type: POSTGRES_16
      diskAutoresize: true
      pointInTimeRecovery: true
      tier: db-f1-micro
      name: spokelse
      databases:
      - name: spokelse
        envVarPrefix: DATABASE
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spokelse-v1
  - name: KAFKA_RESET_POLICY
    value: earliest
  - name: INFOTRYGD_SCOPE
    value: api://dev-fss.tbd.sparkel-sykepengeperioder-api/.default
  - name: INFOTRYGD_URL
    value: https://sykepengeperioder-api.dev-fss-pub.nais.io

