apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spokelse
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-dev
  webproxy: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  accessPolicy:
    inbound:
      rules:
        - application: fpsak
          namespace: teamforeldrepenger
        - application: fprisk
          namespace: teamforeldrepenger
        - application: fpabakus
          namespace: default
        - application: sparenaproxy
          namespace: default
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/azure_old
        kvPath: /azuread/data/dev/creds/spokelse
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spokelse-v1
  - name: KAFKA_RESET_POLICY
    value: earliest
  - name: DATABASE_HOST
    value: b27dbvl013.preprod.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spokelse
  - name: DATABASE_VAULT_MOUNT_PATH
    value: postgresql/preprod-fss/
  - name: sparenaproxy_client_id
    value: 8e294ba4-f37c-4cb9-871b-cce06f63e0b9
  - name: fpabakus_client_id
    value: bad91a5b-d155-4c06-ae7f-40dec7d433eb
  - name: fprisk_client_id
    value: c0c74984-1f8a-4a02-bc3f-d4154c8a57d0
  - name: fpsak_client_id
    value: 5ff7aed5-6e15-4e48-a502-a9d025e9cd4b
