apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spokelse
  namespace: default
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/spokelse/default
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvspokelse
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /azuread/data/prod/creds/spokelse
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
  - name: KAFKA_RAPID_TOPIC
    value: helse-rapid-v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: spokelse-v8
  - name: KAFKA_RESET_POLICY
    value: earliest
  - name: DATABASE_HOST
    value: a01dbvl009.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spokelse
  - name: DATABASE_VAULT_MOUNT_PATH
    value: postgresql/prod-fss/
  - name: DISCOVERY_URL
    value: https://login.microsoftonline.com/62366534-1ec3-4962-8869-9b5535279d0b/v2.0/.well-known/openid-configuration
  - name: REQUIRED_GROUP
    value: 611669fa-de5c-4dc2-a0e8-6041a019992a
