apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sparkel-sykepengeperioder
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  webproxy: true
  secureLogs:
    enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/sparkel-sykepengeperioder/default
      - mountPath: /var/run/secrets/nais.io/azure
        kvPath: /azuread/data/prod/creds/sparkel-sykepengeperioder
      - mountPath: /var/run/secrets/nais.io/service_user
        kvPath: /serviceuser/data/prod/srvsparkelsykepeng
  env:
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
  - name: KAFKA_CONSUMER_GROUP_ID
    value: sparkel-sykepengeperioder-v1
  - name: KAFKA_RAPID_TOPIC
    value: helse-rapid-v1
  - name: AZURE_TENANT_ID
    value: 62366534-1ec3-4962-8869-9b5535279d0b
  - name: AZURE_TENANT_BASEURL
    value: https://login.microsoftonline.com
  - name: INFOTRYGD_SCOPE
    value: api://847deffa-0b46-4b8f-ae79-c7773ee3dfb3/.default
  - name: INFOTRYGD_URL
    value: http://infotrygd-sykepenger.default.svc.nais.local
