apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spokelse
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  ingresses:
  - https://spokelse.intern.nav.no
  resources:
    limits:
      cpu: 3000m
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 256Mi
  replicas:
    min: 3
    max: 6
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: fpsak
          namespace: teamforeldrepenger
          cluster: prod-fss
        - application: fprisk
          namespace: teamforeldrepenger
          cluster: prod-fss
        - application: fpabakus
          namespace: teamforeldrepenger
          cluster: prod-fss
        - application: spissnok
          namespace: tbd
        - application: spapi
          namespace: tbd
    outbound:
      external:
        - host: sykepengeperioder-api.prod-fss-pub.nais.io
  gcp:
    sqlInstances:
    - type: POSTGRES_14
      diskAutoresize: true
      pointInTimeRecovery: true
      tier: db-custom-1-3840
      name: spokelse
      databases:
      - name: spokelse
        envVarPrefix: DATABASE
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spokelse-v1
  - name: KAFKA_RESET_POLICY
    value: none
  - name: INFOTRYGD_SCOPE
    value: api://prod-fss.tbd.sykepengeperioder-api/.default
  - name: INFOTRYGD_URL
    value: https://sykepengeperioder-api.prod-fss-pub.nais.io
