apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spokelse
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  preStopHook:
    http:
      path: /stop
  ingresses:
    - https://spokelse.intern.nav.no
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 3
    max: 6
  strategy:
      rollingUpdate:
        maxSurge: 2 # ruller ut to nye podder samtidig
        maxUnavailable: 1 # terminerer en pod samtidig som de nye rulles ut
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: fpsak
          namespace: teamforeldrepenger
          cluster: prod-fss
          permissions:
            roles:
              - "foreldrepenger-les"
        - application: fprisk
          namespace: teamforeldrepenger
          cluster: prod-fss
          permissions:
            roles:
              - "foreldrepenger-les"
        - application: fpabakus
          namespace: teamforeldrepenger
          cluster: prod-fss
          permissions:
            roles:
              - "foreldrepenger-les"
        - application: spapi
          permissions:
            roles:
              - "spleiselaget-les"
        - application: k9-abakus
          namespace: k9saksbehandling
          cluster: prod-fss
          permissions:
            roles:
              - "k9-les"
        - application: behandlingsflyt
          namespace: aap
          cluster: prod-gcp
          permissions:
            roles:
              - "aap-les"
        - application: dp-oppslag-ytelser
          namespace: teamdagpenger
          cluster: prod-gcp
          permissions:
            roles:
              - "dagpenger-les"
    outbound:
      rules:
        - application: logging
          namespace: nais-system
      external:
        - host: sykepengeperioder-api.prod-fss-pub.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        pointInTimeRecovery: true
        tier: db-custom-1-3840
        name: spokelse
        databases:
          - name: spokelse
            envVarPrefix: DATABASE
  env:
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: tbd-spokelse-v1
    - name: KAFKA_RESET_POLICY
      value: none
    - name: INFOTRYGD_SCOPE
      value: api://prod-fss.tbd.sparkel-sykepengeperioder-api/.default
    - name: INFOTRYGD_URL
      value: https://sykepengeperioder-api.prod-fss-pub.nais.io
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
