apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spokelse
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  resources:
    limits:
      cpu: 3000m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  replicas:
    min: 1
    max: 6
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  kafka:
    pool: nav-prod
  webproxy: true
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: fpsak
          namespace: teamforeldrepenger
        - application: fprisk
          namespace: teamforeldrepenger
        - application: fpabakus
          namespace: default
        - application: sparenaproxy
          namespace: teamsykmelding
        - application: spissnok
          namespace: tbd
  vault:
    enabled: true
  env:
  - name: KAFKA_RAPID_TOPIC
    value: tbd.rapid.v1
  - name: KAFKA_CONSUMER_GROUP_ID
    value: tbd-spokelse-v1
  - name: KAFKA_RESET_POLICY
    value: none
  - name: DATABASE_HOST
    value: a01dbvl009.adeo.no
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: spokelse
  - name: DATABASE_VAULT_MOUNT_PATH
    value: postgresql/prod-fss/
