name: master

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: create image tag
      run: echo "IMAGE=ghcr.io/${{ github.repository }}/spokelse:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17.x'
        cache: 'gradle'
    - name: test and build
      run: ./gradlew test build -i
    - name: build docker image
      run: docker build . --pull -t ${IMAGE}
    - name: push docker image
      run: |
        docker login --username "$GITHUB_REPOSITORY" -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker push ${IMAGE}

  deployDev:
    name: Deploy to dev
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create image tag
        run: echo "IMAGE=ghcr.io/${{ github.repository }}/spokelse:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: deploy/dev.yml

  deployProd:
    name: Deploy to prod
    needs: [build, deployDev]
    runs-on: ubuntu-latest
    steps:
      - name: Create image tag
        run: echo "IMAGE=ghcr.io/${{ github.repository }}/spokelse:$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: deploy/prod.yml
